### ISSUE TITLE
Application is not supported for this API version

### ISSUE THREAD

**Issue by sekhar4233** [AzureADQuickStarts/B2C-GraphAPI-DotNet#1]
Getting below error when running this application with my B2C app tenant.

AADSTS70001: Application  is not supported for this API version.
Trace ID: 0e310471-b1a4-4df7-96ed-5d0e102ead22
Correlation ID: 9f4d2225-259c-4f85-adcc-cba4d916ff17
Timestamp: 2015-10-20 11:48:11Z

**Comment by AlexanderViken** [comment]
I have the same issue. with not supported API version.

AADSTS70001: Application 'a67470eb-2243-4f5f-8063-4d715ae54922' is not supported for this API version.
Trace ID: 8429bab4-304d-41c9-96e9-c7ad168b3d35
Correlation ID: ba3bbadd-289c-4b3a-bbe6-2ecacdda8ebc
Timestamp: 2015-11-10 09:40:57Z

**Comment by Mimetis** [comment]
Same as well

**Comment by xaguzman** [comment]
also facing this issue, has anyone found a solution for this?

**Comment by miteshpatekar** [comment]
Still facing this issue

**Comment by smokedlinq** [comment]
Problem here too.

**Comment by miteshpatekar** [comment]
I have found an alternative solution for this, go to azure classic old portal -> your b2c active directory -> applications tab-> select "Application my company owns" ->click on b2c_extensions_app .
And use the client credentials of this app to access the api.
It will work.

**Comment by akshay-nakra** [comment]
Same issue ! it was working fine 2 months back

**Comment by BlueCloudDev** [comment]
Using miteshpatekar's solution worked for me. Since everything is stored at the directory level, I don't think it'll be an issue to use this for GraphAPI authentication instead of the application itself.

**Comment by whatsdis** [comment]
still happening for me

**Comment by dstrockis** [comment]
Sorry for missing this....  This happens when you attempt to use an application registered in the Azure AD B2C portal to call the Graph API.  You need to follow the instructions at https://azure.microsoft.com/en-us/documentation/articles/active-directory-b2c-devquickstarts-graph-dotnet/ to create an application using Powershell and use that to call the Graph API.
