### ISSUE TITLE
GetAllUsers not acquiring all users

### ISSUE THREAD

**Issue by dominicusmento** [AzureADQuickStarts/B2C-GraphAPI-DotNet#17]
GetAllUsers() does not acquire all users but only 'first' (or better be said 'some') 100 users. This function either should be called differently or should handle odata.nextLink property returned from the graph api. When the link is returned, there is a bit of problem with splitting the path and query part so the parameters can be sent correctly. This is a bit tricky because the SendGraphRequest functions adds manually '?api-version=1.6' and the url which is returned from graph already contains query. I think that implementation of Uri parameter maybe can solve some tricky parts here.

**Comment by derisen** [comment]
Closing as we are archiving this repo. Please refer to instead: [Azure AD B2C user account management with .NET Core and Microsoft Graph](https://github.com/Azure-Samples/ms-identity-dotnetcore-b2c-account-management)
