### ISSUE TITLE
Authorization_RequestDenied

### ISSUE THREAD

**Issue by lengqi127** [AzureADQuickStarts/B2C-GraphAPI-DotNet#22]
Error Calling the Graph API:
{
  "odata.error": {
    "code": "Authorization_RequestDenied",
    "message": {
      "lang": "en",
      "value": "Insufficient privileges to complete the operation."
    },
    "requestId": "d84ef9fe-45ee-4b64-be69-3e6feb332ad1",
    "date": "2019-12-29T12:18:39"
  }
}

**Comment by yasinkavakli** [comment]
I'm getting this one while trying to update a user too. Even when trying to read a users data.

Can someone please help out with all the needed privileges?

**Comment by Bunnywood** [comment]
I have the same issue after following the documentation.

Some idea of how to fix it would allow me to continue evaluating AAD B2C. 

Thanks.

**Comment by jmprieur** [comment]
@Bunnywood : you cannot call Microsoft Graph with AAD B2C. you need to use AAD.
The samples are available from https://aka.ms/aaddevsamplesv2

**Comment by jmprieur** [comment]
Oh sorry this is for user management. I suggest you have a look at https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-user-migration?tabs=applications

**Comment by derisen** [comment]
Closing as we are archiving this repo. Please refer to instead: [Azure AD B2C user account management with .NET Core and Microsoft Graph](https://github.com/Azure-Samples/ms-identity-dotnetcore-b2c-account-management)
