### ISSUE TITLE
Please update references

### ISSUE THREAD

**Issue by sven5** [AzureADQuickStarts/B2C-GraphAPI-DotNet#23]
It would be great if someone could update the references to reflect current APIs.
For instance, `AcquireToken `changed to `AcquireTokenAsync`

**Comment by derisen** [comment]
Closing as we are archiving this repo. Please refer to instead: [Azure AD B2C user account management with .NET Core and Microsoft Graph](https://github.com/Azure-Samples/ms-identity-dotnetcore-b2c-account-management)
