### ISSUE TITLE
Specifying email address when creating a new user with username

### ISSUE THREAD

**Issue by jtrotman10** [AzureADQuickStarts/B2C-GraphAPI-DotNet#24]
If the B2C LocalAccount IdentityProvider is set to use "Username" (as opposed to email), how do you specify the email address required for password reset? The regular susi user flow collects a username and email address, but the usertemplate-username.json file doesn't show an email address and if I CREATE-USER using this template, the user is created with no email (as you'd expect)?

**Comment by derisen** [comment]
Closing as we are archiving this repo. Please refer to instead: [Azure AD B2C user account management with .NET Core and Microsoft Graph](https://github.com/Azure-Samples/ms-identity-dotnetcore-b2c-account-management)
