### ISSUE TITLE
Error One or more properties contains invalid values

### ISSUE THREAD

**Issue by tombs** [AzureADQuickStarts/B2C-GraphAPI-DotNet#3]
Hi. I've followed the instructions to the letter, downloaded the sample DotNet application, and for the most part, it works. I was able to login to my B2C account in PowerShell, and I am able to obtain users from our directory. But I was trying to create a new user using the example, less the comments.

{

"accountEnabled": true,
"alternativeSignInNamesInfo": [
{
"type": "emailAddress", 
"value": "joeconsumer@gmail.com"
}
],
"creationType": "NameCoexistence",
"displayName": "Joe Consumer", 
"mailNickname": "joec", 
"passwordProfile": {
"password": "P@ssword!",
"forceChangePasswordNextLogin": false
},
"passwordPolicies": "DisablePasswordExpiration"
}

and I encounter this error.

Error Calling the Graph API:
{
"odata.error": {
"code": "Request_BadRequest",
"message": {
"lang": "en",
"value": "One or more properties contains invalid values."
},
"values": null
}
}

I've checked the requirements, https://msdn.microsoft.com/Lib..., and these are correct.

Let me know if you require more information.

**Comment by dstrockis** [comment]
Hi tombs, going to close this for now since it's so old, sorry for missing it.  If your still having problems please re-open and I'll be happy to help out.
