### ISSUE TITLE
No client secret for native client apps

### ISSUE THREAD

**Issue by elvogel** [AzureADQuickStarts/B2C-GraphAPI-DotNet#5]
When I go to register the app with my client, I'm given the option of enabling a Web App / Web API and a Native client. When I enable the Native client, I'm given a Redirect URI that looks like:
urn:ietf:wg:oauth:2.0:oob

But there is no client secret anywhere. If I enable the Web App Web API feature I am given a prompt to enter Reply URLs and redirect URIs, which doesn't let me use the one I'm given. The App key created also doesn't work as a client secret. 

Where do I get the client secret from?

**Comment by dstrockis** [comment]
Please follow the instructions at https://azure.microsoft.com/en-us/documentation/articles/active-directory-b2c-devquickstarts-graph-dotnet/

**Comment by elvogel** [comment]
thank you!
