### ISSUE TITLE
B2C Get-B2C-Application output empty

### ISSUE THREAD

**Issue by scout208** [AzureADQuickStarts/B2C-GraphAPI-DotNet#7]
Following the tutorial on [this](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet) page, get to the section titled 'Use Custom Attributes'. Defined my custom attribute by following the instructions listed [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-custom-attr). 

But typing `B2C Get-B2C-Application` returns

    GET https://graph.windows.net/monarctest.onmicrosoft.com/applications?api-    version=1.6&$filter=displayName eq 'b2c-extensions-app'
    Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ilk0dWVLMm9hSU5RaVFiNVlFQlNZVnlEY3BB...
    
    200: OK
    
    {
      "odata.metadata":     "https://graph.windows.net/monarctest.onmicrosoft.com/$metadata#directoryObjects",
      "value": []
    }

and I don't know why.

**Comment by rndthoughts** [comment]
Its because the name has been changed and so the query to find the extension doesnt find it. I have a pull request open to update the code.

**Comment by rndthoughts** [comment]
https://github.com/AzureADQuickStarts/B2C-GraphAPI-DotNet/pull/9

**Comment by gsacavdm** [comment]
Closing now that we've merged #9
